def PSoption1():
    SSide = float(input("Please enter the smallest side:  "))
    LSide = float(input("Please enter the Longest side:  "))
    A2 = (SSide * SSide)
    B2 = (LSide * LSide)
    FindHypotenuse = (A2 + B2)
    FindHypotenuse = (FindHypotenuse ** 0.5)
    print ("The answer is:" , FindHypotenuse)
def PSoption2():
    LSide = float(input("Please enter the Longest side:  "))
    Hypotenuse = float(input("Please enter the Hypotenuse:  "))
    B2 = (LSide * LSide)
    C2 = (Hypotenuse * Hypotenuse)
    FindSSide = (C2 - B2)
    FindSSide = (FindSSide ** 0.5)
    print ("The answer is:" , FindSSide)
def PSoption3():
    SSide = float(input("Please enter the smallest side:  "))
    Hypotenuse = float(input("Please enter the Hypotenuse:  "))
    A2 = (SSide * SSide)
    C2 = (Hypotenuse * Hypotenuse)
    FindLSide = (C2 - A2)
    FindLSide = (FindLSide ** 0.5)
    print ("The answer is:" , FindLSide)